id: I6982887B
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T14:52:42.685891'
last_modified: '2022-05-27T14:52:42.685907'
parser: null
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: zh
  base:
    fCC81:
      title: Complete text
      base_file: fCC81.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
